#!/usr/bin/sage -python

"""
Requirements:
    Start Pycharm from sage shell
    Execute the script from command line
"""
from sage.all import *
import numpy as np

var('x')
S = solve(x**3-1 == 0, x)
print(S[0])